name: CI-Release

on:
  pull_request:
    types: [ opened, reopened ]
  push:
    branches:
      - master

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and cache Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: build binary
        run: |
          docker run --rm -v ${PWD}:/project builder make
      - name: create distribution .zip
        run: |
          docker run --rm -v ${PWD}:/project builder make dist
      - uses: actions/upload-artifact@master
        with:
          name: wafel_installer
          path: "./dist/wiiu/"
  release:
    if: github.ref == 'refs/heads/master'
    needs: build-binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wafel_installer
          path: wafel_installer
      - uses: "softprops/action-gh-release@v1"
        with:
          draft: true
          files: |
            wafel_installer/apps/wafel_installer/wafel_installer.wuhb
            wafel_installer/apps/wafel_installer/wafel_installer.rpx